repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v7.32.0" # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        args:
          - --ignore-pattern '!.eleventy.js'
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
exclude: "static/js/jquery-3.2.1.js|static/js/minesweeper.js"
