repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        args:
          - --score=n
          - -d fixme
          - -d missing-module-docstring
          - -d missing-function-docstring
          - -d import-error
          - -d wrong-import-order
          - -d logging-fstring-interpolation # see https://github.com/PyCQA/pylint/issues/1788
        require_serial: false
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]
