[build]
  publish = "_site/"
  command = "npm run build"

[[redirects]]
  from = "https://dippedrusk.netlify.app"
  to = "https://dippedrusk.com"
  status = 301
  force = true

[[redirects]]
  from = "https://vasundharagautam.com"
  to = "https://dippedrusk.com"
  status = 301
  force = true

[[redirects]]
  from = "https://www.vasundharagautam.com"
  to = "https://dippedrusk.com"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[context.production]
  [[context.production.plugins]]
    package = "netlify-plugin-submit-sitemap"

      [context.production.plugins.inputs]
      sitemapPath = "/sitemap.xml"

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "_site"
  filePath = "sitemap.xml"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  entryPoints = [
    "*.html",
    "*.md",
    "*.njk",
  ]
  recursive = true
  pretty = true
  checkExternal = false
  skipPatterns = [
    "dl.acm.org/doi/"
  ]

[[plugins]]
  package = "@netlify/plugin-a11y"
  [plugins.inputs]
    ignoreElements = 'header > title'
    failWithIssues = true
    wcagLevel = 'WCAG2AAA'

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    accessibility = 1
    best-practices = 1
    seo = 0.96

[[plugins]]
package = "netlify-plugin-no-more-404"
