[build]
  publish = "_site/"
  command = "npm run build"

[[redirects]]
  from = "https://naughty-wilson-684740.netlify.app"
  to = "https://vasundharagautam.com"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  entryPoints = [
    "*.html",
    "*.md",
    "*.njk",
  ]
  recursive = true
  pretty = true
  checkExternal = true
  skipPatterns = [
    "dl.acm.org/doi/"
  ]

[[plugins]]
  package = "@netlify/plugin-a11y"
  [plugins.inputs]
    failWithIssues = false
    wcagLevel = 'WCAG2AAA'
