version: 2.1
orbs:
  linter: talkiq/linter@1
  node: circleci/node@4.7

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.10
          filters:
            tags:
              only: /.*/
      - node/run:
          npm-run: build
          name: build-site
